version: '3.5'

services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile.base
      context: .
    command: python /app/main.py
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - ~/.config:/root/.config
